### ISSUE TITLE
Классификация персонажей

### ISSUE THREAD

**Issue by iillyyaa2033** [iillyyaa2033/nmud-docs#2]
Не согласен [про демонов](https://github.com/iillyyaa2033/nmud-docs/blob/master/ru/%D0%A0%D0%B0%D1%81%D1%8B%20%D0%B8%20%D0%BF%D0%B5%D1%80%D1%81%D0%BE%D0%BD%D0%B0%D0%B6%D0%B8/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%86%D0%B8%D1%8F%20%D0%BF%D0%B5%D1%80%D1%81%D0%BE%D0%BD%D0%B0%D0%B6%D0%B5%D0%B9.txt). Почему ад классический? Не, ну лава там, жара - это все понятно. Но боль и страдания? В нашей концепции жители поверхности вроде как не попадают в инферно/мечту, верно? А своих мучить 'за так' нет резона - проще либо сразу прибить, либо держать под контролем.

**Comment by iillyyaa2033** [comment]
@klessh, про этот issue помнишь?

**Comment by klessh** [comment]
Тогда куда они попадают? Кого-никого можно похищать. Идея была в следующем: сделать ад, в первую очередь, рациональным местом, одновременно соблюсти классические черты, но развить эту тему. Хоть кто-то должен попадатб в ад. И то инферно, про которое говорил я, рядом с мечтой или в стороне, но никак не часть её. Нравится мне эта тема.

**Comment by iillyyaa2033** [comment]
Куда попадают грешники? Никуда: просто умирают. Я считаю - это забавнее.

Как добраться до инферны? Есть три пути:
1. Прокопаться до пещерного слоя, пройти его - и вот ты там. Как вариант: спуститься через разлом.
2. Телепортнуться.
3. На крайнем юге, где очень жарко, инферна и поверхность сближаются, буквально пять метров песка (или песчаника) - и вот уже верхний уровень инферно.

**Comment by klessh** [comment]
Это обсуждали. Я тогда согласился с твоей идеей, решил оставить свою на потом...

**Comment by iillyyaa2033** [comment]
Тогда - вопрос решен.
